export const teams2021 = {
  status: true,
  data: {
    name: "English Premier League",
    abbreviation: "Prem",
    seasonDisplay: "2021-2022",
    season: 2021,
    standings: [
      {
        team: {
          id: "382",
          uid: "s:600~t:382",
          location: "Manchester City",
          name: "Manchester City",
          abbreviation: "MNC",
          displayName: "Manchester City",
          shortDisplayName: "Man City",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        note: {
          color: "#81D6AC",
          description: "Champions League",
          rank: 1,
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 18,
            displayValue: "18",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 2,
            displayValue: "2",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 2,
            displayValue: "2",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 22,
            displayValue: "22",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 54,
            displayValue: "54",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 13,
            displayValue: "13",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 56,
            displayValue: "56",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 1,
            displayValue: "1",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: 41,
            displayValue: "+41",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "18-2-2",
            displayValue: "18-2-2",
          },
        ],
      },
      {
        team: {
          id: "364",
          uid: "s:600~t:364",
          location: "Liverpool",
          name: "Liverpool",
          abbreviation: "LIV",
          displayName: "Liverpool",
          shortDisplayName: "Liverpool",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        note: {
          color: "#81D6AC",
          description: "Champions League",
          rank: 2,
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 13,
            displayValue: "13",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 2,
            displayValue: "2",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 6,
            displayValue: "6",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 21,
            displayValue: "21",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 55,
            displayValue: "55",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 18,
            displayValue: "18",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 45,
            displayValue: "45",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 2,
            displayValue: "2",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: 37,
            displayValue: "+37",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "13-6-2",
            displayValue: "13-6-2",
          },
        ],
      },
      {
        team: {
          id: "363",
          uid: "s:600~t:363",
          location: "Chelsea",
          name: "Chelsea",
          abbreviation: "CHE",
          displayName: "Chelsea",
          shortDisplayName: "Chelsea",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        note: {
          color: "#81D6AC",
          description: "Champions League",
          rank: 3,
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 12,
            displayValue: "12",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 3,
            displayValue: "3",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 8,
            displayValue: "8",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 23,
            displayValue: "23",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 46,
            displayValue: "46",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 18,
            displayValue: "18",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 44,
            displayValue: "44",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 3,
            displayValue: "3",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: 28,
            displayValue: "+28",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "12-8-3",
            displayValue: "12-8-3",
          },
        ],
      },
      {
        team: {
          id: "371",
          uid: "s:600~t:371",
          location: "West Ham United",
          name: "West Ham United",
          abbreviation: "WHU",
          displayName: "West Ham United",
          shortDisplayName: "West Ham",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/371.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        note: {
          color: "#81D6AC",
          description: "Champions League",
          rank: 4,
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 11,
            displayValue: "11",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 7,
            displayValue: "7",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 4,
            displayValue: "4",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 22,
            displayValue: "22",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 41,
            displayValue: "41",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 30,
            displayValue: "30",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 37,
            displayValue: "37",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 4,
            displayValue: "4",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: 11,
            displayValue: "+11",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "11-4-7",
            displayValue: "11-4-7",
          },
        ],
      },
      {
        team: {
          id: "359",
          uid: "s:600~t:359",
          location: "Arsenal",
          name: "Arsenal",
          abbreviation: "ARS",
          displayName: "Arsenal",
          shortDisplayName: "Arsenal",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        note: {
          color: "#B2BFD0",
          description: "Europa League",
          rank: 5,
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 11,
            displayValue: "11",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 7,
            displayValue: "7",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 2,
            displayValue: "2",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 20,
            displayValue: "20",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 33,
            displayValue: "33",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 25,
            displayValue: "25",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 35,
            displayValue: "35",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 5,
            displayValue: "5",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: 8,
            displayValue: "+8",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "11-2-7",
            displayValue: "11-2-7",
          },
        ],
      },
      {
        team: {
          id: "367",
          uid: "s:600~t:367",
          location: "Tottenham Hotspur",
          name: "Tottenham Hotspur",
          abbreviation: "TOT",
          displayName: "Tottenham Hotspur",
          shortDisplayName: "Tottenham",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 10,
            displayValue: "10",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 5,
            displayValue: "5",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 3,
            displayValue: "3",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 18,
            displayValue: "18",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 23,
            displayValue: "23",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 20,
            displayValue: "20",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 33,
            displayValue: "33",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 6,
            displayValue: "6",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: 3,
            displayValue: "+3",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "10-3-5",
            displayValue: "10-3-5",
          },
        ],
      },
      {
        team: {
          id: "360",
          uid: "s:600~t:360",
          location: "Manchester United",
          name: "Manchester United",
          abbreviation: "MAN",
          displayName: "Manchester United",
          shortDisplayName: "Man United",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 9,
            displayValue: "9",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 6,
            displayValue: "6",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 5,
            displayValue: "5",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 20,
            displayValue: "20",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 32,
            displayValue: "32",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 29,
            displayValue: "29",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 32,
            displayValue: "32",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 7,
            displayValue: "7",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: 3,
            displayValue: "+3",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "9-5-6",
            displayValue: "9-5-6",
          },
        ],
      },
      {
        team: {
          id: "380",
          uid: "s:600~t:380",
          location: "Wolverhampton Wanderers",
          name: "Wolverhampton Wanderers",
          abbreviation: "WOL",
          displayName: "Wolverhampton Wanderers",
          shortDisplayName: "Wolves",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/380.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 9,
            displayValue: "9",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 7,
            displayValue: "7",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 4,
            displayValue: "4",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 20,
            displayValue: "20",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 17,
            displayValue: "17",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 15,
            displayValue: "15",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 31,
            displayValue: "31",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 8,
            displayValue: "8",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: 2,
            displayValue: "+2",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "9-4-7",
            displayValue: "9-4-7",
          },
        ],
      },
      {
        team: {
          id: "331",
          uid: "s:600~t:331",
          location: "Brighton & Hove Albion",
          name: "Brighton & Hove Albion",
          abbreviation: "BHA",
          displayName: "Brighton & Hove Albion",
          shortDisplayName: "Brighton",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/331.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 6,
            displayValue: "6",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 4,
            displayValue: "4",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 11,
            displayValue: "11",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 21,
            displayValue: "21",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 22,
            displayValue: "22",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 22,
            displayValue: "22",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 29,
            displayValue: "29",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 9,
            displayValue: "9",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: 0,
            displayValue: "0",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "6-11-4",
            displayValue: "6-11-4",
          },
        ],
      },
      {
        team: {
          id: "375",
          uid: "s:600~t:375",
          location: "Leicester City",
          name: "Leicester City",
          abbreviation: "LEI",
          displayName: "Leicester City",
          shortDisplayName: "Leicester",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/375.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 7,
            displayValue: "7",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 7,
            displayValue: "7",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 4,
            displayValue: "4",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 18,
            displayValue: "18",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 31,
            displayValue: "31",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 33,
            displayValue: "33",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 25,
            displayValue: "25",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 10,
            displayValue: "10",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -2,
            displayValue: "-2",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "7-4-7",
            displayValue: "7-4-7",
          },
        ],
      },
      {
        team: {
          id: "384",
          uid: "s:600~t:384",
          location: "Crystal Palace",
          name: "Crystal Palace",
          abbreviation: "CRY",
          displayName: "Crystal Palace",
          shortDisplayName: "C Palace",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/384.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 5,
            displayValue: "5",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 7,
            displayValue: "7",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 9,
            displayValue: "9",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 21,
            displayValue: "21",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 30,
            displayValue: "30",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 31,
            displayValue: "31",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 24,
            displayValue: "24",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 11,
            displayValue: "11",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -1,
            displayValue: "-1",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "5-9-7",
            displayValue: "5-9-7",
          },
        ],
      },
      {
        team: {
          id: "376",
          uid: "s:600~t:376",
          location: "Southampton",
          name: "Southampton",
          abbreviation: "SOU",
          displayName: "Southampton",
          shortDisplayName: "Southampton",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/376.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 5,
            displayValue: "5",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 7,
            displayValue: "7",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 9,
            displayValue: "9",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 21,
            displayValue: "21",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 25,
            displayValue: "25",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 33,
            displayValue: "33",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 24,
            displayValue: "24",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 12,
            displayValue: "12",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -8,
            displayValue: "-8",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "5-9-7",
            displayValue: "5-9-7",
          },
        ],
      },
      {
        team: {
          id: "362",
          uid: "s:600~t:362",
          location: "Aston Villa",
          name: "Aston Villa",
          abbreviation: "AVL",
          displayName: "Aston Villa",
          shortDisplayName: "Aston Villa",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 7,
            displayValue: "7",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 11,
            displayValue: "11",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 2,
            displayValue: "2",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 20,
            displayValue: "20",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 27,
            displayValue: "27",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 32,
            displayValue: "32",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 23,
            displayValue: "23",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 13,
            displayValue: "13",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -5,
            displayValue: "-5",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "7-2-11",
            displayValue: "7-2-11",
          },
        ],
      },
      {
        team: {
          id: "337",
          uid: "s:600~t:337",
          location: "Brentford",
          name: "Brentford",
          abbreviation: "BRE",
          displayName: "Brentford",
          shortDisplayName: "Brentford",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2020-07-16T16:13Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 6,
            displayValue: "6",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 10,
            displayValue: "10",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 5,
            displayValue: "5",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 21,
            displayValue: "21",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 24,
            displayValue: "24",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 33,
            displayValue: "33",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 23,
            displayValue: "23",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 14,
            displayValue: "14",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -9,
            displayValue: "-9",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "6-5-10",
            displayValue: "6-5-10",
          },
        ],
      },
      {
        team: {
          id: "357",
          uid: "s:600~t:357",
          location: "Leeds United",
          name: "Leeds United",
          abbreviation: "LEE",
          displayName: "Leeds United",
          shortDisplayName: "Leeds",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/357.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 5,
            displayValue: "5",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 8,
            displayValue: "8",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 7,
            displayValue: "7",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 20,
            displayValue: "20",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 24,
            displayValue: "24",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 39,
            displayValue: "39",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 22,
            displayValue: "22",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 15,
            displayValue: "15",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -15,
            displayValue: "-15",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "5-7-8",
            displayValue: "5-7-8",
          },
        ],
      },
      {
        team: {
          id: "368",
          uid: "s:600~t:368",
          location: "Everton",
          name: "Everton",
          abbreviation: "EVE",
          displayName: "Everton",
          shortDisplayName: "Everton",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 5,
            displayValue: "5",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 10,
            displayValue: "10",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 4,
            displayValue: "4",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 19,
            displayValue: "19",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 24,
            displayValue: "24",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 34,
            displayValue: "34",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 19,
            displayValue: "19",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 16,
            displayValue: "16",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -10,
            displayValue: "-10",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "5-4-10",
            displayValue: "5-4-10",
          },
        ],
      },
      {
        team: {
          id: "395",
          uid: "s:600~t:395",
          location: "Watford",
          name: "Watford",
          abbreviation: "WAT",
          displayName: "Watford",
          shortDisplayName: "Watford",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/395.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 4,
            displayValue: "4",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 13,
            displayValue: "13",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 2,
            displayValue: "2",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 19,
            displayValue: "19",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 23,
            displayValue: "23",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 37,
            displayValue: "37",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 14,
            displayValue: "14",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 17,
            displayValue: "17",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -14,
            displayValue: "-14",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "4-2-13",
            displayValue: "4-2-13",
          },
        ],
      },
      {
        team: {
          id: "381",
          uid: "s:600~t:381",
          location: "Norwich City",
          name: "Norwich City",
          abbreviation: "NOR",
          displayName: "Norwich City",
          shortDisplayName: "Norwich",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/381.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        note: {
          color: "#FF7F84",
          description: "Relegation",
          rank: 18,
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 3,
            displayValue: "3",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 14,
            displayValue: "14",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 4,
            displayValue: "4",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 21,
            displayValue: "21",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 10,
            displayValue: "10",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 45,
            displayValue: "45",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 13,
            displayValue: "13",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 18,
            displayValue: "18",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -35,
            displayValue: "-35",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "3-4-14",
            displayValue: "3-4-14",
          },
        ],
      },
      {
        team: {
          id: "361",
          uid: "s:600~t:361",
          location: "Newcastle United",
          name: "Newcastle United",
          abbreviation: "NEW",
          displayName: "Newcastle United",
          shortDisplayName: "Newcastle",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/361.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        note: {
          color: "#FF7F84",
          description: "Relegation",
          rank: 19,
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 1,
            displayValue: "1",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 10,
            displayValue: "10",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 9,
            displayValue: "9",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 20,
            displayValue: "20",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 20,
            displayValue: "20",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 43,
            displayValue: "43",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 12,
            displayValue: "12",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 19,
            displayValue: "19",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -23,
            displayValue: "-23",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "1-9-10",
            displayValue: "1-9-10",
          },
        ],
      },
      {
        team: {
          id: "379",
          uid: "s:600~t:379",
          location: "Burnley",
          name: "Burnley",
          abbreviation: "BUR",
          displayName: "Burnley",
          shortDisplayName: "Burnley",
          isActive: true,
          logos: [
            {
              href: "https://a.espncdn.com/i/teamlogos/soccer/500/379.png",
              width: 500,
              height: 500,
              alt: "",
              rel: ["full", "default"],
              lastUpdated: "2019-05-08T16:07Z",
            },
          ],
        },
        note: {
          color: "#FF7F84",
          description: "Relegation",
          rank: 20,
        },
        stats: [
          {
            name: "wins",
            displayName: "Wins",
            shortDisplayName: "W",
            description: "Wins",
            abbreviation: "W",
            type: "wins",
            value: 1,
            displayValue: "1",
          },
          {
            name: "losses",
            displayName: "Losses",
            shortDisplayName: "L",
            description: "Losses",
            abbreviation: "L",
            type: "losses",
            value: 8,
            displayValue: "8",
          },
          {
            name: "ties",
            displayName: "Draws",
            shortDisplayName: "D",
            description: "Draws",
            abbreviation: "D",
            type: "ties",
            value: 8,
            displayValue: "8",
          },
          {
            name: "gamesPlayed",
            displayName: "Games Played",
            shortDisplayName: "GP",
            description: "Games Played",
            abbreviation: "GP",
            type: "gamesplayed",
            value: 17,
            displayValue: "17",
          },
          {
            name: "pointsFor",
            displayName: "Goals For",
            shortDisplayName: "F",
            description: "Goals For",
            abbreviation: "F",
            type: "pointsfor",
            value: 16,
            displayValue: "16",
          },
          {
            name: "pointsAgainst",
            displayName: "Goals Against",
            shortDisplayName: "A",
            description: "Goals Against",
            abbreviation: "A",
            type: "pointsagainst",
            value: 27,
            displayValue: "27",
          },
          {
            name: "points",
            displayName: "Points",
            shortDisplayName: "P",
            description: "Points",
            abbreviation: "P",
            type: "points",
            value: 11,
            displayValue: "11",
          },
          {
            name: "rankChange",
            displayName: "Rank Change",
            shortDisplayName: "Rank Change",
            description: "Rank Change",
            abbreviation: "RC",
            type: "rankchange",
            value: 0,
            displayValue: "0",
          },
          {
            name: "rank",
            displayName: "Rank",
            shortDisplayName: "Rank",
            description: "Rank",
            abbreviation: "R",
            type: "rank",
            value: 20,
            displayValue: "20",
          },
          {
            name: "pointDifferential",
            displayName: "Goal Difference",
            shortDisplayName: "GD",
            description: "Goal Difference",
            abbreviation: "GD",
            type: "pointdifferential",
            value: -11,
            displayValue: "-11",
          },
          {
            name: "deductions",
            displayName: "Point Deductions",
            shortDisplayName: "Deductions",
            description: "Point Deductions",
            abbreviation: "PD",
            type: "deductions",
            value: 0,
            displayValue: "",
          },
          {
            name: "ppg",
            displayName: "Points Per Game",
            shortDisplayName: "PPG",
            description: "Points Per Game",
            abbreviation: "PPG",
            type: "ppg",
            value: 0,
            displayValue: "0",
          },
          {
            id: "0",
            name: "All Splits",
            abbreviation: "Total",
            displayName: "Overall",
            shortDisplayName: "OVER",
            description: "Overall Record",
            type: "total",
            summary: "1-8-8",
            displayValue: "1-8-8",
          },
        ],
      },
    ],
  },
};
