const topscorers2020 = {
  get: "players/topscorers",
  parameters: {
    league: "39",
    season: "2020",
  },
  errors: [],
  results: 20,
  paging: {
    current: 0,
    total: 1,
  },
  response: [
    {
      player: {
        id: 184,
        name: "H. Kane",
        firstname: "Harry",
        lastname: "Kane",
        age: 29,
        birth: {
          date: "1993-07-28",
          place: "London",
          country: "England",
        },
        nationality: "England",
        height: "188 cm",
        weight: "86 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/184.png",
      },
      statistics: [
        {
          team: {
            id: 47,
            name: "Tottenham",
            logo: "https://media.api-sports.io/football/teams/47.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 35,
            lineups: 35,
            minutes: 3087,
            number: null,
            position: "Attacker",
            rating: "7.642857",
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 5,
            bench: 0,
          },
          shots: {
            total: 110,
            on: 53,
          },
          goals: {
            total: 23,
            conceded: 0,
            assists: 14,
            saves: null,
          },
          passes: {
            total: 909,
            key: 51,
            accuracy: 18,
          },
          tackles: {
            total: 22,
            blocks: 11,
            interceptions: 11,
          },
          duels: {
            total: 466,
            won: 209,
          },
          dribbles: {
            attempts: 100,
            success: 52,
            past: null,
          },
          fouls: {
            drawn: 60,
            committed: 26,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 4,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 306,
        name: "Mohamed Salah",
        firstname: "Mohamed",
        lastname: "Salah Ghaly",
        age: 30,
        birth: {
          date: "1992-06-15",
          place: "Muḥāfaẓat al Gharbiyya",
          country: "Egypt",
        },
        nationality: "Egypt",
        height: "175 cm",
        weight: "71 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/306.png",
      },
      statistics: [
        {
          team: {
            id: 40,
            name: "Liverpool",
            logo: "https://media.api-sports.io/football/teams/40.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 37,
            lineups: 34,
            minutes: 3082,
            number: null,
            position: "Attacker",
            rating: "7.159459",
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 7,
            bench: 3,
          },
          shots: {
            total: 90,
            on: 52,
          },
          goals: {
            total: 22,
            conceded: 0,
            assists: 5,
            saves: null,
          },
          passes: {
            total: 1262,
            key: 58,
            accuracy: 28,
          },
          tackles: {
            total: 18,
            blocks: null,
            interceptions: 1,
          },
          duels: {
            total: 297,
            won: 94,
          },
          dribbles: {
            attempts: 84,
            success: 36,
            past: null,
          },
          fouls: {
            drawn: 22,
            committed: 22,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 6,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 1485,
        name: "Bruno Fernandes",
        firstname: "Bruno Miguel",
        lastname: "Borges Fernandes",
        age: 28,
        birth: {
          date: "1994-09-08",
          place: "Maia",
          country: "Portugal",
        },
        nationality: "Portugal",
        height: "179 cm",
        weight: "69 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/1485.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 37,
            lineups: 35,
            minutes: 3109,
            number: null,
            position: "Midfielder",
            rating: "7.564864",
            captain: false,
          },
          substitutes: {
            in: 2,
            out: 12,
            bench: 2,
          },
          shots: {
            total: 84,
            on: 51,
          },
          goals: {
            total: 18,
            conceded: 0,
            assists: 12,
            saves: null,
          },
          passes: {
            total: 2109,
            key: 97,
            accuracy: 44,
          },
          tackles: {
            total: 57,
            blocks: null,
            interceptions: 26,
          },
          duels: {
            total: 364,
            won: 147,
          },
          dribbles: {
            attempts: 45,
            success: 23,
            past: null,
          },
          fouls: {
            drawn: 52,
            committed: 43,
          },
          cards: {
            yellow: 6,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 9,
            missed: 1,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 186,
        name: "Son Heung-Min",
        firstname: "Heung-Min",
        lastname: "Son",
        age: 30,
        birth: {
          date: "1992-07-08",
          place: "Chuncheon",
          country: "Korea Republic",
        },
        nationality: "Korea Republic",
        height: "183 cm",
        weight: "78 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/186.png",
      },
      statistics: [
        {
          team: {
            id: 47,
            name: "Tottenham",
            logo: "https://media.api-sports.io/football/teams/47.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 37,
            lineups: 36,
            minutes: 3126,
            number: null,
            position: "Midfielder",
            rating: "7.267567",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 13,
            bench: 1,
          },
          shots: {
            total: 53,
            on: 36,
          },
          goals: {
            total: 17,
            conceded: 0,
            assists: 10,
            saves: null,
          },
          passes: {
            total: 1056,
            key: 76,
            accuracy: 23,
          },
          tackles: {
            total: 32,
            blocks: 3,
            interceptions: 14,
          },
          duels: {
            total: 357,
            won: 144,
          },
          dribbles: {
            attempts: 72,
            success: 39,
            past: null,
          },
          fouls: {
            drawn: 54,
            committed: 14,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 1,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 19134,
        name: "P. Bamford",
        firstname: "Patrick",
        lastname: "Bamford",
        age: 29,
        birth: {
          date: "1993-09-05",
          place: "Grantham",
          country: "England",
        },
        nationality: "England",
        height: "185 cm",
        weight: "71 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/19134.png",
      },
      statistics: [
        {
          team: {
            id: 63,
            name: "Leeds",
            logo: "https://media.api-sports.io/football/teams/63.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 38,
            lineups: 37,
            minutes: 3062,
            number: null,
            position: "Attacker",
            rating: "6.963157",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 13,
            bench: 1,
          },
          shots: {
            total: 90,
            on: 47,
          },
          goals: {
            total: 17,
            conceded: 0,
            assists: 7,
            saves: null,
          },
          passes: {
            total: 509,
            key: 30,
            accuracy: 10,
          },
          tackles: {
            total: 21,
            blocks: 4,
            interceptions: 10,
          },
          duels: {
            total: 279,
            won: 110,
          },
          dribbles: {
            attempts: 40,
            success: 19,
            past: null,
          },
          fouls: {
            drawn: 23,
            committed: 36,
          },
          cards: {
            yellow: 3,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 2,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 18766,
        name: "D. Calvert-Lewin",
        firstname: "Dominic",
        lastname: "Calvert-Lewin",
        age: 25,
        birth: {
          date: "1997-03-16",
          place: "Sheffield",
          country: "England",
        },
        nationality: "England",
        height: "187 cm",
        weight: "71 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/18766.png",
      },
      statistics: [
        {
          team: {
            id: 45,
            name: "Everton",
            logo: "https://media.api-sports.io/football/teams/45.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 33,
            lineups: 32,
            minutes: 2876,
            number: null,
            position: "Attacker",
            rating: "7.103030",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 6,
            bench: 1,
          },
          shots: {
            total: 72,
            on: 46,
          },
          goals: {
            total: 16,
            conceded: 0,
            assists: null,
            saves: null,
          },
          passes: {
            total: 675,
            key: 18,
            accuracy: 14,
          },
          tackles: {
            total: 17,
            blocks: 6,
            interceptions: 6,
          },
          duels: {
            total: 463,
            won: 233,
          },
          dribbles: {
            attempts: 49,
            success: 22,
            past: null,
          },
          fouls: {
            drawn: 41,
            committed: 37,
          },
          cards: {
            yellow: 3,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 18788,
        name: "J. Vardy",
        firstname: "Jamie",
        lastname: "Vardy",
        age: 35,
        birth: {
          date: "1987-01-11",
          place: "Sheffield",
          country: "England",
        },
        nationality: "England",
        height: "179 cm",
        weight: "74 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/18788.png",
      },
      statistics: [
        {
          team: {
            id: 46,
            name: "Leicester",
            logo: "https://media.api-sports.io/football/teams/46.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 34,
            lineups: 31,
            minutes: 2845,
            number: null,
            position: "Attacker",
            rating: "7.123529",
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 7,
            bench: 3,
          },
          shots: {
            total: 67,
            on: 38,
          },
          goals: {
            total: 15,
            conceded: 0,
            assists: 9,
            saves: null,
          },
          passes: {
            total: 434,
            key: 28,
            accuracy: 8,
          },
          tackles: {
            total: 18,
            blocks: 5,
            interceptions: 4,
          },
          duels: {
            total: 251,
            won: 119,
          },
          dribbles: {
            attempts: 41,
            success: 26,
            past: null,
          },
          fouls: {
            drawn: 25,
            committed: 26,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 8,
            missed: 1,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 19366,
        name: "O. Watkins",
        firstname: "Ollie",
        lastname: "Watkins",
        age: 27,
        birth: {
          date: "1995-12-30",
          place: "Torbay",
          country: "England",
        },
        nationality: "England",
        height: "180 cm",
        weight: "70 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/19366.png",
      },
      statistics: [
        {
          team: {
            id: 66,
            name: "Aston Villa",
            logo: "https://media.api-sports.io/football/teams/66.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 37,
            lineups: 37,
            minutes: 3329,
            number: null,
            position: "Attacker",
            rating: "7.048648",
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 0,
            bench: 0,
          },
          shots: {
            total: 72,
            on: 46,
          },
          goals: {
            total: 14,
            conceded: 0,
            assists: 5,
            saves: null,
          },
          passes: {
            total: 806,
            key: 45,
            accuracy: 15,
          },
          tackles: {
            total: 30,
            blocks: 2,
            interceptions: 7,
          },
          duels: {
            total: 590,
            won: 254,
          },
          dribbles: {
            attempts: 69,
            success: 39,
            past: null,
          },
          fouls: {
            drawn: 49,
            committed: 47,
          },
          cards: {
            yellow: 3,
            yellowred: 1,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 1,
            missed: 1,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 633,
        name: "İ. Gündoğan",
        firstname: "İlkay",
        lastname: "Gündoğan",
        age: 32,
        birth: {
          date: "1990-10-24",
          place: "Gelsenkirchen",
          country: "Germany",
        },
        nationality: "Germany",
        height: "180 cm",
        weight: "80 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/633.png",
      },
      statistics: [
        {
          team: {
            id: 50,
            name: "Manchester City",
            logo: "https://media.api-sports.io/football/teams/50.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 28,
            lineups: 23,
            minutes: 2031,
            number: null,
            position: "Midfielder",
            rating: "7.332142",
            captain: false,
          },
          substitutes: {
            in: 5,
            out: 7,
            bench: 11,
          },
          shots: {
            total: 43,
            on: 22,
          },
          goals: {
            total: 13,
            conceded: 0,
            assists: 2,
            saves: null,
          },
          passes: {
            total: 1714,
            key: 42,
            accuracy: 56,
          },
          tackles: {
            total: 25,
            blocks: 4,
            interceptions: 20,
          },
          duels: {
            total: 164,
            won: 89,
          },
          dribbles: {
            attempts: 39,
            success: 27,
            past: null,
          },
          fouls: {
            drawn: 26,
            committed: 8,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 1,
            missed: 1,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 1467,
        name: "A. Lacazette",
        firstname: "Alexandre",
        lastname: "Lacazette",
        age: 31,
        birth: {
          date: "1991-05-28",
          place: "Lyon",
          country: "France",
        },
        nationality: "France",
        height: "175 cm",
        weight: "73 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/1467.png",
      },
      statistics: [
        {
          team: {
            id: 42,
            name: "Arsenal",
            logo: "https://media.api-sports.io/football/teams/42.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 31,
            lineups: 22,
            minutes: 1930,
            number: null,
            position: "Attacker",
            rating: "7.022580",
            captain: false,
          },
          substitutes: {
            in: 9,
            out: 15,
            bench: 14,
          },
          shots: {
            total: 40,
            on: 29,
          },
          goals: {
            total: 13,
            conceded: 0,
            assists: 2,
            saves: null,
          },
          passes: {
            total: 514,
            key: 23,
            accuracy: 13,
          },
          tackles: {
            total: 18,
            blocks: 1,
            interceptions: 12,
          },
          duels: {
            total: 282,
            won: 121,
          },
          dribbles: {
            attempts: 36,
            success: 22,
            past: null,
          },
          fouls: {
            drawn: 54,
            committed: 37,
          },
          cards: {
            yellow: 3,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 3,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 2778,
        name: "K. Ịheanachọ",
        firstname: "Kelechi Promise",
        lastname: "Ịheanachọ",
        age: 26,
        birth: {
          date: "1996-10-03",
          place: "Owerri",
          country: "Nigeria",
        },
        nationality: "Nigeria",
        height: "185 cm",
        weight: "82 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/2778.png",
      },
      statistics: [
        {
          team: {
            id: 46,
            name: "Leicester",
            logo: "https://media.api-sports.io/football/teams/46.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 25,
            lineups: 16,
            minutes: 1456,
            number: null,
            position: "Attacker",
            rating: "7.072727",
            captain: false,
          },
          substitutes: {
            in: 9,
            out: 6,
            bench: 22,
          },
          shots: {
            total: 39,
            on: 25,
          },
          goals: {
            total: 12,
            conceded: 0,
            assists: 2,
            saves: null,
          },
          passes: {
            total: 504,
            key: 28,
            accuracy: 16,
          },
          tackles: {
            total: 12,
            blocks: null,
            interceptions: 2,
          },
          duels: {
            total: 182,
            won: 64,
          },
          dribbles: {
            attempts: 44,
            success: 32,
            past: null,
          },
          fouls: {
            drawn: 13,
            committed: 26,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 1,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 18955,
        name: "D. Ings",
        firstname: "Daniel William John",
        lastname: "Ings",
        age: 30,
        birth: {
          date: "1992-07-23",
          place: "Winchester",
          country: "England",
        },
        nationality: "England",
        height: "178 cm",
        weight: "73 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/18955.png",
      },
      statistics: [
        {
          team: {
            id: 41,
            name: "Southampton",
            logo: "https://media.api-sports.io/football/teams/41.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 29,
            lineups: 26,
            minutes: 2183,
            number: null,
            position: "Attacker",
            rating: "6.955172",
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 13,
            bench: 3,
          },
          shots: {
            total: 45,
            on: 27,
          },
          goals: {
            total: 12,
            conceded: 0,
            assists: 4,
            saves: null,
          },
          passes: {
            total: 501,
            key: 22,
            accuracy: 11,
          },
          tackles: {
            total: 22,
            blocks: 2,
            interceptions: 3,
          },
          duels: {
            total: 245,
            won: 93,
          },
          dribbles: {
            attempts: 59,
            success: 30,
            past: null,
          },
          fouls: {
            drawn: 18,
            committed: 19,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 2,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 18931,
        name: "C. Wood",
        firstname: "Christopher Grant",
        lastname: "Wood",
        age: 31,
        birth: {
          date: "1991-12-07",
          place: "Auckland",
          country: "New Zealand",
        },
        nationality: "New Zealand",
        height: "191 cm",
        weight: "81 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/18931.png",
      },
      statistics: [
        {
          team: {
            id: 44,
            name: "Burnley",
            logo: "https://media.api-sports.io/football/teams/44.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 33,
            lineups: 32,
            minutes: 2750,
            number: null,
            position: "Attacker",
            rating: "6.781818",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 10,
            bench: 1,
          },
          shots: {
            total: 56,
            on: 39,
          },
          goals: {
            total: 12,
            conceded: 0,
            assists: 3,
            saves: null,
          },
          passes: {
            total: 653,
            key: 22,
            accuracy: 12,
          },
          tackles: {
            total: 12,
            blocks: 3,
            interceptions: 1,
          },
          duels: {
            total: 488,
            won: 194,
          },
          dribbles: {
            attempts: 21,
            success: 7,
            past: null,
          },
          fouls: {
            drawn: 22,
            committed: 38,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 2,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 2939,
        name: "C. Wilson",
        firstname: "Callum",
        lastname: "Wilson",
        age: 30,
        birth: {
          date: "1992-02-27",
          place: "Coventry",
          country: "England",
        },
        nationality: "England",
        height: "180 cm",
        weight: "66 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/2939.png",
      },
      statistics: [
        {
          team: {
            id: 34,
            name: "Newcastle",
            logo: "https://media.api-sports.io/football/teams/34.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 26,
            lineups: 23,
            minutes: 2085,
            number: null,
            position: "Attacker",
            rating: "6.992307",
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 4,
            bench: 4,
          },
          shots: {
            total: 40,
            on: 20,
          },
          goals: {
            total: 12,
            conceded: 0,
            assists: 5,
            saves: null,
          },
          passes: {
            total: 341,
            key: 17,
            accuracy: 9,
          },
          tackles: {
            total: 12,
            blocks: 3,
            interceptions: 7,
          },
          duels: {
            total: 320,
            won: 122,
          },
          dribbles: {
            attempts: 43,
            success: 26,
            past: null,
          },
          fouls: {
            drawn: 41,
            committed: 40,
          },
          cards: {
            yellow: 2,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 4,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 909,
        name: "M. Rashford",
        firstname: "Marcus",
        lastname: "Rashford",
        age: 25,
        birth: {
          date: "1997-10-31",
          place: "Manchester",
          country: "England",
        },
        nationality: "England",
        height: "180 cm",
        weight: "70 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/909.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 37,
            lineups: 33,
            minutes: 2927,
            number: null,
            position: "Attacker",
            rating: "6.902702",
            captain: false,
          },
          substitutes: {
            in: 4,
            out: 11,
            bench: 5,
          },
          shots: {
            total: 58,
            on: 37,
          },
          goals: {
            total: 11,
            conceded: 0,
            assists: 9,
            saves: null,
          },
          passes: {
            total: 1188,
            key: 43,
            accuracy: 26,
          },
          tackles: {
            total: 18,
            blocks: 2,
            interceptions: 8,
          },
          duels: {
            total: 361,
            won: 167,
          },
          dribbles: {
            attempts: 163,
            success: 82,
            past: null,
          },
          fouls: {
            drawn: 42,
            committed: 25,
          },
          cards: {
            yellow: 4,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 304,
        name: "S. Mané",
        firstname: "Sadio",
        lastname: "Mané",
        age: 30,
        birth: {
          date: "1992-04-10",
          place: "Sedhiou",
          country: "Senegal",
        },
        nationality: "Senegal",
        height: "175 cm",
        weight: "69 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/304.png",
      },
      statistics: [
        {
          team: {
            id: 40,
            name: "Liverpool",
            logo: "https://media.api-sports.io/football/teams/40.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 35,
            lineups: 31,
            minutes: 2812,
            number: null,
            position: "Attacker",
            rating: "7.222857",
            captain: false,
          },
          substitutes: {
            in: 4,
            out: 6,
            bench: 4,
          },
          shots: {
            total: 71,
            on: 36,
          },
          goals: {
            total: 11,
            conceded: 0,
            assists: 7,
            saves: null,
          },
          passes: {
            total: 1006,
            key: 60,
            accuracy: 22,
          },
          tackles: {
            total: 48,
            blocks: null,
            interceptions: 15,
          },
          duels: {
            total: 498,
            won: 243,
          },
          dribbles: {
            attempts: 144,
            success: 82,
            past: null,
          },
          fouls: {
            drawn: 78,
            committed: 53,
          },
          cards: {
            yellow: 3,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 758,
        name: "G. Bale",
        firstname: "Gareth Frank",
        lastname: "Bale",
        age: 33,
        birth: {
          date: "1989-07-16",
          place: "Cardiff",
          country: "Wales",
        },
        nationality: "Wales",
        height: "185 cm",
        weight: "81 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/758.png",
      },
      statistics: [
        {
          team: {
            id: 47,
            name: "Tottenham",
            logo: "https://media.api-sports.io/football/teams/47.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 20,
            lineups: 10,
            minutes: 921,
            number: null,
            position: "Attacker",
            rating: "7.478947",
            captain: false,
          },
          substitutes: {
            in: 10,
            out: 10,
            bench: 20,
          },
          shots: {
            total: 32,
            on: 19,
          },
          goals: {
            total: 11,
            conceded: 0,
            assists: 2,
            saves: null,
          },
          passes: {
            total: 366,
            key: 21,
            accuracy: 14,
          },
          tackles: {
            total: 17,
            blocks: 2,
            interceptions: 8,
          },
          duels: {
            total: 132,
            won: 76,
          },
          dribbles: {
            attempts: 49,
            success: 27,
            past: null,
          },
          fouls: {
            drawn: 9,
            committed: 9,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 3247,
        name: "W. Zaha",
        firstname: "Wilfried",
        lastname: "Zaha",
        age: 30,
        birth: {
          date: "1992-11-10",
          place: "Abidjan",
          country: "Côte d'Ivoire",
        },
        nationality: "Côte d'Ivoire",
        height: "180 cm",
        weight: "66 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/3247.png",
      },
      statistics: [
        {
          team: {
            id: 52,
            name: "Crystal Palace",
            logo: "https://media.api-sports.io/football/teams/52.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 30,
            lineups: 29,
            minutes: 2613,
            number: null,
            position: "Attacker",
            rating: "6.943333",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 2,
            bench: 1,
          },
          shots: {
            total: 37,
            on: 20,
          },
          goals: {
            total: 11,
            conceded: 0,
            assists: 2,
            saves: null,
          },
          passes: {
            total: 734,
            key: 30,
            accuracy: 19,
          },
          tackles: {
            total: 26,
            blocks: null,
            interceptions: 9,
          },
          duels: {
            total: 393,
            won: 178,
          },
          dribbles: {
            attempts: 117,
            success: 55,
            past: null,
          },
          fouls: {
            drawn: 88,
            committed: 32,
          },
          cards: {
            yellow: 6,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 2,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 25618,
        name: "Matheus Fellipe Costa Pereira",
        firstname: "Matheus Fellipe",
        lastname: "Costa Pereira",
        age: 26,
        birth: {
          date: "1996-05-05",
          place: "Belo Horizonte",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "175 cm",
        weight: "66 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/25618.png",
      },
      statistics: [
        {
          team: {
            id: 60,
            name: "West Brom",
            logo: "https://media.api-sports.io/football/teams/60.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 33,
            lineups: 30,
            minutes: 2582,
            number: null,
            position: "Midfielder",
            rating: "7.193939",
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 8,
            bench: 3,
          },
          shots: {
            total: 51,
            on: 28,
          },
          goals: {
            total: 11,
            conceded: 0,
            assists: 6,
            saves: null,
          },
          passes: {
            total: 939,
            key: 60,
            accuracy: 22,
          },
          tackles: {
            total: 26,
            blocks: null,
            interceptions: 29,
          },
          duels: {
            total: 318,
            won: 131,
          },
          dribbles: {
            attempts: 74,
            success: 40,
            past: null,
          },
          fouls: {
            drawn: 52,
            committed: 34,
          },
          cards: {
            yellow: 2,
            yellowred: 0,
            red: 1,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 4,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 645,
        name: "R. Sterling",
        firstname: "Raheem",
        lastname: "Sterling",
        age: 28,
        birth: {
          date: "1994-12-08",
          place: "Kingston",
          country: "Jamaica",
        },
        nationality: "England",
        height: "170 cm",
        weight: "69 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/645.png",
      },
      statistics: [
        {
          team: {
            id: 50,
            name: "Manchester City",
            logo: "https://media.api-sports.io/football/teams/50.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2020,
          },
          games: {
            appearences: 31,
            lineups: 28,
            minutes: 2537,
            number: null,
            position: "Attacker",
            rating: "6.890322",
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 3,
            bench: 8,
          },
          shots: {
            total: 49,
            on: 28,
          },
          goals: {
            total: 10,
            conceded: 0,
            assists: 7,
            saves: null,
          },
          passes: {
            total: 1113,
            key: 40,
            accuracy: 30,
          },
          tackles: {
            total: 21,
            blocks: null,
            interceptions: 15,
          },
          duels: {
            total: 338,
            won: 137,
          },
          dribbles: {
            attempts: 122,
            success: 66,
            past: null,
          },
          fouls: {
            drawn: 41,
            committed: 36,
          },
          cards: {
            yellow: 4,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 1,
            saved: null,
          },
        },
      ],
    },
  ],
};

export default topscorers2020;
