const topscorers2021 = {
  get: "players/topscorers",
  parameters: {
    league: "39",
    season: "2021",
  },
  errors: [],
  results: 20,
  paging: {
    current: 0,
    total: 1,
  },
  response: [
    {
      player: {
        id: 306,
        name: "Mohamed Salah",
        firstname: "Mohamed",
        lastname: "Salah Ghaly",
        age: 30,
        birth: {
          date: "1992-06-15",
          place: "Muḥāfaẓat al Gharbiyya",
          country: "Egypt",
        },
        nationality: "Egypt",
        height: "175 cm",
        weight: "71 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/306.png",
      },
      statistics: [
        {
          team: {
            id: 40,
            name: "Liverpool",
            logo: "https://media.api-sports.io/football/teams/40.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 20,
            lineups: 20,
            minutes: 1784,
            number: null,
            position: "Attacker",
            rating: "7.547368",
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 2,
            bench: 0,
          },
          shots: {
            total: 56,
            on: 35,
          },
          goals: {
            total: 16,
            conceded: 0,
            assists: 9,
            saves: null,
          },
          passes: {
            total: 647,
            key: 39,
            accuracy: 27,
          },
          tackles: {
            total: 9,
            blocks: null,
            interceptions: 4,
          },
          duels: {
            total: 188,
            won: 66,
          },
          dribbles: {
            attempts: 78,
            success: 37,
            past: null,
          },
          fouls: {
            drawn: 15,
            committed: 6,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 2,
            missed: 1,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 2678,
        name: "Diogo Jota",
        firstname: "Diogo José",
        lastname: "Teixeira da Silva",
        age: 26,
        birth: {
          date: "1996-12-04",
          place: "Massarelos",
          country: "Portugal",
        },
        nationality: "Portugal",
        height: "178 cm",
        weight: "68 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/2678.png",
      },
      statistics: [
        {
          team: {
            id: 40,
            name: "Liverpool",
            logo: "https://media.api-sports.io/football/teams/40.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 20,
            lineups: 17,
            minutes: 1463,
            number: null,
            position: "Attacker",
            rating: "7.068421",
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 13,
            bench: 4,
          },
          shots: {
            total: 45,
            on: 21,
          },
          goals: {
            total: 10,
            conceded: 0,
            assists: 1,
            saves: null,
          },
          passes: {
            total: 427,
            key: 24,
            accuracy: 17,
          },
          tackles: {
            total: 22,
            blocks: 2,
            interceptions: 3,
          },
          duels: {
            total: 229,
            won: 90,
          },
          dribbles: {
            attempts: 37,
            success: 16,
            past: null,
          },
          fouls: {
            drawn: 26,
            committed: 23,
          },
          cards: {
            yellow: 1,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 18788,
        name: "J. Vardy",
        firstname: "Jamie",
        lastname: "Vardy",
        age: 35,
        birth: {
          date: "1987-01-11",
          place: "Sheffield",
          country: "England",
        },
        nationality: "England",
        height: "179 cm",
        weight: "74 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/18788.png",
      },
      statistics: [
        {
          team: {
            id: 46,
            name: "Leicester",
            logo: "https://media.api-sports.io/football/teams/46.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 16,
            lineups: 15,
            minutes: 1322,
            number: null,
            position: "Attacker",
            rating: "7.093750",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 2,
            bench: 3,
          },
          shots: {
            total: 30,
            on: 16,
          },
          goals: {
            total: 9,
            conceded: 0,
            assists: 1,
            saves: null,
          },
          passes: {
            total: 182,
            key: 14,
            accuracy: 8,
          },
          tackles: {
            total: 1,
            blocks: null,
            interceptions: 1,
          },
          duels: {
            total: 95,
            won: 35,
          },
          dribbles: {
            attempts: 13,
            success: 8,
            past: null,
          },
          fouls: {
            drawn: 10,
            committed: 7,
          },
          cards: {
            yellow: 2,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 18819,
        name: "M. Antonio",
        firstname: "Michail",
        lastname: "Antonio",
        age: 32,
        birth: {
          date: "1990-03-28",
          place: "London",
          country: "England",
        },
        nationality: "Jamaica",
        height: "180 cm",
        weight: "82 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/18819.png",
      },
      statistics: [
        {
          team: {
            id: 48,
            name: "West Ham",
            logo: "https://media.api-sports.io/football/teams/48.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 21,
            lineups: 20,
            minutes: 1841,
            number: null,
            position: "Midfielder",
            rating: "7.047619",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 4,
            bench: 1,
          },
          shots: {
            total: 38,
            on: 19,
          },
          goals: {
            total: 8,
            conceded: 0,
            assists: 6,
            saves: null,
          },
          passes: {
            total: 400,
            key: 36,
            accuracy: 12,
          },
          tackles: {
            total: 13,
            blocks: null,
            interceptions: 2,
          },
          duels: {
            total: 306,
            won: 116,
          },
          dribbles: {
            attempts: 54,
            success: 28,
            past: null,
          },
          fouls: {
            drawn: 33,
            committed: 34,
          },
          cards: {
            yellow: 5,
            yellowred: 1,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 1,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 80,
        name: "E. Dennis",
        firstname: "Emmanuel Bonaventure",
        lastname: "Dennis",
        age: 25,
        birth: {
          date: "1997-11-15",
          place: "Abuja",
          country: "Nigeria",
        },
        nationality: "Nigeria",
        height: "174 cm",
        weight: "67 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/80.png",
      },
      statistics: [
        {
          team: {
            id: 38,
            name: "Watford",
            logo: "https://media.api-sports.io/football/teams/38.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 18,
            lineups: 17,
            minutes: 1394,
            number: null,
            position: "Attacker",
            rating: "7.005555",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 9,
            bench: 1,
          },
          shots: {
            total: 27,
            on: 19,
          },
          goals: {
            total: 8,
            conceded: 0,
            assists: 5,
            saves: null,
          },
          passes: {
            total: 310,
            key: 20,
            accuracy: 11,
          },
          tackles: {
            total: 29,
            blocks: 2,
            interceptions: 7,
          },
          duels: {
            total: 289,
            won: 111,
          },
          dribbles: {
            attempts: 73,
            success: 31,
            past: null,
          },
          fouls: {
            drawn: 21,
            committed: 39,
          },
          cards: {
            yellow: 6,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 186,
        name: "Son Heung-Min",
        firstname: "Heung-Min",
        lastname: "Son",
        age: 30,
        birth: {
          date: "1992-07-08",
          place: "Chuncheon",
          country: "Korea Republic",
        },
        nationality: "Korea Republic",
        height: "183 cm",
        weight: "78 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/186.png",
      },
      statistics: [
        {
          team: {
            id: 47,
            name: "Tottenham",
            logo: "https://media.api-sports.io/football/teams/47.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 17,
            lineups: 17,
            minutes: 1488,
            number: null,
            position: "Midfielder",
            rating: "7.288235",
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 5,
            bench: 0,
          },
          shots: {
            total: 34,
            on: 20,
          },
          goals: {
            total: 8,
            conceded: 0,
            assists: 3,
            saves: null,
          },
          passes: {
            total: 555,
            key: 32,
            accuracy: 27,
          },
          tackles: {
            total: 5,
            blocks: 1,
            interceptions: 6,
          },
          duels: {
            total: 149,
            won: 60,
          },
          dribbles: {
            attempts: 49,
            success: 28,
            past: null,
          },
          fouls: {
            drawn: 14,
            committed: 7,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 1161,
        name: "E. Smith Rowe",
        firstname: "Emile",
        lastname: "Smith Rowe",
        age: 22,
        birth: {
          date: "2000-07-28",
          place: "Croydon",
          country: "England",
        },
        nationality: "England",
        height: "182 cm",
        weight: "79 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/1161.png",
      },
      statistics: [
        {
          team: {
            id: 42,
            name: "Arsenal",
            logo: "https://media.api-sports.io/football/teams/42.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 18,
            lineups: 13,
            minutes: 1206,
            number: null,
            position: "Midfielder",
            rating: "7.094444",
            captain: false,
          },
          substitutes: {
            in: 5,
            out: 5,
            bench: 6,
          },
          shots: {
            total: 20,
            on: 16,
          },
          goals: {
            total: 8,
            conceded: 0,
            assists: 2,
            saves: null,
          },
          passes: {
            total: 467,
            key: 20,
            accuracy: 22,
          },
          tackles: {
            total: 7,
            blocks: 1,
            interceptions: 11,
          },
          duels: {
            total: 101,
            won: 47,
          },
          dribbles: {
            attempts: 35,
            success: 23,
            past: null,
          },
          fouls: {
            drawn: 12,
            committed: 3,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 304,
        name: "S. Mané",
        firstname: "Sadio",
        lastname: "Mané",
        age: 30,
        birth: {
          date: "1992-04-10",
          place: "Sedhiou",
          country: "Senegal",
        },
        nationality: "Senegal",
        height: "175 cm",
        weight: "69 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/304.png",
      },
      statistics: [
        {
          team: {
            id: 40,
            name: "Liverpool",
            logo: "https://media.api-sports.io/football/teams/40.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 20,
            lineups: 19,
            minutes: 1714,
            number: null,
            position: "Attacker",
            rating: "7.005263",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 3,
            bench: 1,
          },
          shots: {
            total: 35,
            on: 20,
          },
          goals: {
            total: 8,
            conceded: 0,
            assists: 1,
            saves: null,
          },
          passes: {
            total: 563,
            key: 22,
            accuracy: 22,
          },
          tackles: {
            total: 22,
            blocks: null,
            interceptions: 7,
          },
          duels: {
            total: 210,
            won: 88,
          },
          dribbles: {
            attempts: 47,
            success: 27,
            past: null,
          },
          fouls: {
            drawn: 24,
            committed: 30,
          },
          cards: {
            yellow: 2,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 874,
        name: "Cristiano Ronaldo",
        firstname: "Cristiano Ronaldo",
        lastname: "dos Santos Aveiro",
        age: 37,
        birth: {
          date: "1985-02-05",
          place: "Funchal",
          country: "Portugal",
        },
        nationality: "Portugal",
        height: "187 cm",
        weight: "83 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/874.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 17,
            lineups: 15,
            minutes: 1369,
            number: null,
            position: "Attacker",
            rating: "7.118750",
            captain: false,
          },
          substitutes: {
            in: 2,
            out: 4,
            bench: 2,
          },
          shots: {
            total: 41,
            on: 20,
          },
          goals: {
            total: 8,
            conceded: 0,
            assists: 3,
            saves: null,
          },
          passes: {
            total: 435,
            key: 11,
            accuracy: 21,
          },
          tackles: {
            total: 3,
            blocks: null,
            interceptions: 1,
          },
          duels: {
            total: 119,
            won: 46,
          },
          dribbles: {
            attempts: 19,
            success: 12,
            past: null,
          },
          fouls: {
            drawn: 12,
            committed: 9,
          },
          cards: {
            yellow: 4,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 2,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 1496,
        name: "Raphinha",
        firstname: "Raphael",
        lastname: "Dias Belloli",
        age: 26,
        birth: {
          date: "1996-12-14",
          place: "Porto Alegre",
          country: "Brazil",
        },
        nationality: "Brazil",
        height: "176 cm",
        weight: "58 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/1496.png",
      },
      statistics: [
        {
          team: {
            id: 63,
            name: "Leeds",
            logo: "https://media.api-sports.io/football/teams/63.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 18,
            lineups: 18,
            minutes: 1531,
            number: null,
            position: "Attacker",
            rating: "7.064705",
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 4,
            bench: 0,
          },
          shots: {
            total: 35,
            on: 16,
          },
          goals: {
            total: 8,
            conceded: 0,
            assists: 2,
            saves: null,
          },
          passes: {
            total: 528,
            key: 37,
            accuracy: 21,
          },
          tackles: {
            total: 27,
            blocks: null,
            interceptions: 17,
          },
          duels: {
            total: 231,
            won: 102,
          },
          dribbles: {
            attempts: 87,
            success: 40,
            past: null,
          },
          fouls: {
            drawn: 23,
            committed: 22,
          },
          cards: {
            yellow: 4,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 3,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 1485,
        name: "Bruno Fernandes",
        firstname: "Bruno Miguel",
        lastname: "Borges Fernandes",
        age: 28,
        birth: {
          date: "1994-09-08",
          place: "Maia",
          country: "Portugal",
        },
        nationality: "Portugal",
        height: "179 cm",
        weight: "69 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/1485.png",
      },
      statistics: [
        {
          team: {
            id: 33,
            name: "Manchester United",
            logo: "https://media.api-sports.io/football/teams/33.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 20,
            lineups: 19,
            minutes: 1685,
            number: null,
            position: "Midfielder",
            rating: "7.363157",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 8,
            bench: 1,
          },
          shots: {
            total: 28,
            on: 12,
          },
          goals: {
            total: 7,
            conceded: 0,
            assists: 5,
            saves: null,
          },
          passes: {
            total: 976,
            key: 53,
            accuracy: 39,
          },
          tackles: {
            total: 28,
            blocks: null,
            interceptions: 8,
          },
          duels: {
            total: 184,
            won: 73,
          },
          dribbles: {
            attempts: 26,
            success: 11,
            past: null,
          },
          fouls: {
            drawn: 23,
            committed: 20,
          },
          cards: {
            yellow: 6,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 1,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 67972,
        name: "C. Gallagher",
        firstname: "Conor",
        lastname: "Gallagher",
        age: 22,
        birth: {
          date: "2000-02-06",
          place: "Epsom",
          country: "England",
        },
        nationality: "England",
        height: null,
        weight: null,
        injured: false,
        photo: "https://media.api-sports.io/football/players/67972.png",
      },
      statistics: [
        {
          team: {
            id: 52,
            name: "Crystal Palace",
            logo: "https://media.api-sports.io/football/teams/52.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 18,
            lineups: 18,
            minutes: 1574,
            number: null,
            position: "Midfielder",
            rating: "7.470588",
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 4,
            bench: 0,
          },
          shots: {
            total: 27,
            on: 15,
          },
          goals: {
            total: 7,
            conceded: 0,
            assists: 3,
            saves: null,
          },
          passes: {
            total: 569,
            key: 31,
            accuracy: 27,
          },
          tackles: {
            total: 48,
            blocks: 5,
            interceptions: 12,
          },
          duels: {
            total: 219,
            won: 111,
          },
          dribbles: {
            attempts: 38,
            success: 22,
            past: null,
          },
          fouls: {
            drawn: 29,
            committed: 28,
          },
          cards: {
            yellow: 4,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 636,
        name: "Bernardo Silva",
        firstname: "Bernardo",
        lastname: "Mota Veiga de Carvalho e Silva",
        age: 28,
        birth: {
          date: "1994-08-10",
          place: "Lisboa",
          country: "Portugal",
        },
        nationality: "Portugal",
        height: "173 cm",
        weight: "64 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/636.png",
      },
      statistics: [
        {
          team: {
            id: 50,
            name: "Manchester City",
            logo: "https://media.api-sports.io/football/teams/50.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 21,
            lineups: 21,
            minutes: 1796,
            number: null,
            position: "Midfielder",
            rating: "7.228571",
            captain: false,
          },
          substitutes: {
            in: 0,
            out: 4,
            bench: 1,
          },
          shots: {
            total: 20,
            on: 14,
          },
          goals: {
            total: 7,
            conceded: 0,
            assists: 1,
            saves: null,
          },
          passes: {
            total: 1187,
            key: 32,
            accuracy: 50,
          },
          tackles: {
            total: 37,
            blocks: 1,
            interceptions: 9,
          },
          duels: {
            total: 195,
            won: 100,
          },
          dribbles: {
            attempts: 61,
            success: 35,
            past: null,
          },
          fouls: {
            drawn: 23,
            committed: 19,
          },
          cards: {
            yellow: 5,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 19220,
        name: "M. Mount",
        firstname: "Mason",
        lastname: "Mount",
        age: 23,
        birth: {
          date: "1999-01-10",
          place: "Portsmouth",
          country: "England",
        },
        nationality: "England",
        height: "178 cm",
        weight: "70 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/19220.png",
      },
      statistics: [
        {
          team: {
            id: 49,
            name: "Chelsea",
            logo: "https://media.api-sports.io/football/teams/49.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 20,
            lineups: 15,
            minutes: 1346,
            number: null,
            position: "Midfielder",
            rating: "7.336842",
            captain: false,
          },
          substitutes: {
            in: 5,
            out: 3,
            bench: 6,
          },
          shots: {
            total: 25,
            on: 18,
          },
          goals: {
            total: 7,
            conceded: 0,
            assists: 5,
            saves: null,
          },
          passes: {
            total: 543,
            key: 28,
            accuracy: 24,
          },
          tackles: {
            total: 26,
            blocks: null,
            interceptions: 9,
          },
          duels: {
            total: 130,
            won: 50,
          },
          dribbles: {
            attempts: 29,
            success: 10,
            past: null,
          },
          fouls: {
            drawn: 10,
            committed: 13,
          },
          cards: {
            yellow: 2,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 1,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 19364,
        name: "N. Maupay",
        firstname: "Neal",
        lastname: "Maupay",
        age: 26,
        birth: {
          date: "1996-08-14",
          place: "Versailles",
          country: "France",
        },
        nationality: "France",
        height: "173 cm",
        weight: "69 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/19364.png",
      },
      statistics: [
        {
          team: {
            id: 51,
            name: "Brighton",
            logo: "https://media.api-sports.io/football/teams/51.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 19,
            lineups: 16,
            minutes: 1406,
            number: null,
            position: "Attacker",
            rating: "6.823529",
            captain: false,
          },
          substitutes: {
            in: 3,
            out: 3,
            bench: 4,
          },
          shots: {
            total: 26,
            on: 9,
          },
          goals: {
            total: 7,
            conceded: 0,
            assists: null,
            saves: null,
          },
          passes: {
            total: 294,
            key: 13,
            accuracy: 13,
          },
          tackles: {
            total: 10,
            blocks: 2,
            interceptions: 1,
          },
          duels: {
            total: 133,
            won: 44,
          },
          dribbles: {
            attempts: 19,
            success: 10,
            past: null,
          },
          fouls: {
            drawn: 16,
            committed: 12,
          },
          cards: {
            yellow: 4,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 1,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 645,
        name: "R. Sterling",
        firstname: "Raheem",
        lastname: "Sterling",
        age: 28,
        birth: {
          date: "1994-12-08",
          place: "Kingston",
          country: "Jamaica",
        },
        nationality: "England",
        height: "170 cm",
        weight: "69 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/645.png",
      },
      statistics: [
        {
          team: {
            id: 50,
            name: "Manchester City",
            logo: "https://media.api-sports.io/football/teams/50.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 18,
            lineups: 12,
            minutes: 1183,
            number: null,
            position: "Attacker",
            rating: "6.977777",
            captain: false,
          },
          substitutes: {
            in: 6,
            out: 2,
            bench: 9,
          },
          shots: {
            total: 29,
            on: 17,
          },
          goals: {
            total: 7,
            conceded: 0,
            assists: 1,
            saves: null,
          },
          passes: {
            total: 489,
            key: 25,
            accuracy: 23,
          },
          tackles: {
            total: 17,
            blocks: null,
            interceptions: 7,
          },
          duels: {
            total: 159,
            won: 65,
          },
          dribbles: {
            attempts: 63,
            success: 26,
            past: null,
          },
          fouls: {
            drawn: 20,
            committed: 10,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 2,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 19428,
        name: "J. Bowen",
        firstname: "Jarrod",
        lastname: "Bowen",
        age: 26,
        birth: {
          date: "1996-12-20",
          place: "Leominster",
          country: "England",
        },
        nationality: "England",
        height: null,
        weight: null,
        injured: false,
        photo: "https://media.api-sports.io/football/players/19428.png",
      },
      statistics: [
        {
          team: {
            id: 48,
            name: "West Ham",
            logo: "https://media.api-sports.io/football/teams/48.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 22,
            lineups: 21,
            minutes: 1863,
            number: null,
            position: "Attacker",
            rating: "7.022727",
            captain: false,
          },
          substitutes: {
            in: 1,
            out: 10,
            bench: 1,
          },
          shots: {
            total: 39,
            on: 23,
          },
          goals: {
            total: 6,
            conceded: 0,
            assists: 7,
            saves: null,
          },
          passes: {
            total: 453,
            key: 29,
            accuracy: 15,
          },
          tackles: {
            total: 28,
            blocks: 2,
            interceptions: 15,
          },
          duels: {
            total: 251,
            won: 114,
          },
          dribbles: {
            attempts: 65,
            success: 38,
            past: null,
          },
          fouls: {
            drawn: 28,
            committed: 17,
          },
          cards: {
            yellow: 2,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 1460,
        name: "B. Saka",
        firstname: "Bukayo",
        lastname: "Saka",
        age: 21,
        birth: {
          date: "2001-09-05",
          place: "London",
          country: "England",
        },
        nationality: "England",
        height: "178 cm",
        weight: "65 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/1460.png",
      },
      statistics: [
        {
          team: {
            id: 42,
            name: "Arsenal",
            logo: "https://media.api-sports.io/football/teams/42.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 20,
            lineups: 18,
            minutes: 1490,
            number: null,
            position: "Attacker",
            rating: "6.945000",
            captain: false,
          },
          substitutes: {
            in: 2,
            out: 11,
            bench: 2,
          },
          shots: {
            total: 27,
            on: 14,
          },
          goals: {
            total: 6,
            conceded: 0,
            assists: 4,
            saves: null,
          },
          passes: {
            total: 550,
            key: 32,
            accuracy: 21,
          },
          tackles: {
            total: 18,
            blocks: null,
            interceptions: 7,
          },
          duels: {
            total: 180,
            won: 80,
          },
          dribbles: {
            attempts: 44,
            success: 20,
            past: null,
          },
          fouls: {
            drawn: 33,
            committed: 13,
          },
          cards: {
            yellow: 3,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 18784,
        name: "J. Maddison",
        firstname: "James",
        lastname: "Maddison",
        age: 26,
        birth: {
          date: "1996-11-23",
          place: "Coventry",
          country: "England",
        },
        nationality: "England",
        height: "175 cm",
        weight: "73 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/18784.png",
      },
      statistics: [
        {
          team: {
            id: 46,
            name: "Leicester",
            logo: "https://media.api-sports.io/football/teams/46.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 19,
            lineups: 15,
            minutes: 1258,
            number: null,
            position: "Midfielder",
            rating: "7.168421",
            captain: false,
          },
          substitutes: {
            in: 4,
            out: 11,
            bench: 4,
          },
          shots: {
            total: 32,
            on: 20,
          },
          goals: {
            total: 6,
            conceded: 0,
            assists: 3,
            saves: null,
          },
          passes: {
            total: 425,
            key: 21,
            accuracy: 17,
          },
          tackles: {
            total: 18,
            blocks: 2,
            interceptions: 5,
          },
          duels: {
            total: 130,
            won: 70,
          },
          dribbles: {
            attempts: 26,
            success: 15,
            past: null,
          },
          fouls: {
            drawn: 33,
            committed: 5,
          },
          cards: {
            yellow: 2,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 629,
        name: "K. De Bruyne",
        firstname: "Kevin",
        lastname: "De Bruyne",
        age: 31,
        birth: {
          date: "1991-06-28",
          place: "Drongen",
          country: "Belgium",
        },
        nationality: "Belgium",
        height: "181 cm",
        weight: "68 kg",
        injured: false,
        photo: "https://media.api-sports.io/football/players/629.png",
      },
      statistics: [
        {
          team: {
            id: 50,
            name: "Manchester City",
            logo: "https://media.api-sports.io/football/teams/50.png",
          },
          league: {
            id: 39,
            name: "Premier League",
            country: "England",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            flag: "https://media.api-sports.io/flags/gb.svg",
            season: 2021,
          },
          games: {
            appearences: 16,
            lineups: 11,
            minutes: 1007,
            number: null,
            position: "Midfielder",
            rating: "7.506250",
            captain: false,
          },
          substitutes: {
            in: 5,
            out: 5,
            bench: 6,
          },
          shots: {
            total: 26,
            on: 13,
          },
          goals: {
            total: 6,
            conceded: 0,
            assists: 1,
            saves: null,
          },
          passes: {
            total: 623,
            key: 38,
            accuracy: 32,
          },
          tackles: {
            total: 17,
            blocks: 2,
            interceptions: 3,
          },
          duels: {
            total: 93,
            won: 50,
          },
          dribbles: {
            attempts: 28,
            success: 17,
            past: null,
          },
          fouls: {
            drawn: 12,
            committed: 4,
          },
          cards: {
            yellow: 0,
            yellowred: 0,
            red: 0,
          },
          penalty: {
            won: null,
            commited: null,
            scored: 0,
            missed: 0,
            saved: null,
          },
        },
      ],
    },
  ],
};

export default topscorers2021;
